# .github/actions/setup-java/action.yml
name: "Setup Java Environment"
description: "Sets up Java and masks paths"
inputs:
  java-distribution:
    description: "Distribution of Java to use"
    required: true
  java-version:
    description: "Version of Java to install"
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: ${{ inputs.java-distribution }}
        java-version: ${{ inputs.java-version }}
      env:
        ACTIONS_STEP_DEBUG: false
        ACTIONS_RUNNER_DEBUG: false
