# .github/actions/setup-db-init/action.yml
name: "Setup Database Initialization"
description: "Creates the database initialization script"
runs:
  using: "composite"
  steps:
    - name: Create initialization script
      shell: bash
      run: |
        cat << EOF > init-keycloak-db.sh
        #!/bin/bash
        set -e

        psql -v ON_ERROR_STOP=1 --username "\$POSTGRES_USER" --dbname "\$POSTGRES_DB" <<-EOSQL
            CREATE DATABASE keycloak;
            GRANT ALL PRIVILEGES ON DATABASE keycloak TO \$POSTGRES_USER;
        EOSQL
        EOF
        chmod +x init-keycloak-db.sh
